### ISSUE TITLE
Little bugs

### ISSUE THREAD

**Issue by Weefle** [BurnyDaKath/OMGPI#6]
Hey, why there is only one map to vote in GUI when I created two "lol" and "test", it disply me only a paper for "lol": http://bit.ly/2u3fwi2
The kit slot selection is buggy: http://bit.ly/2t5xaVj
I get this error several times (spam) after a game, on prelobby: https://hastebin.com/fedexirico.vbs
Can you fix this error or prevent it from appearing: https://hastebin.com/osuyakayek.md
The rightclick for "/options" command is buggy when the player isn't opped, the GUI can works or not sometimes.
I have this type of error too after game, on prelobby: https://hastebin.com/wihoqelege.sql

**Comment by BurnyDaKath** [comment]
Kit slot is not buggy, item missing meaning that slot is selected. Click other item to swap selected slot with other one.

Cannot fix error because it does not come from my plugins, it comes from minecraft server internals which i could not fix. Not even mute the error. Smart developers may come and contribute the fix, but until then, i could not figure out one.

> The rightclick for "/options" command is buggy when the player isn't opped, the GUI can works or not sometimes.

Cannot figure out problem (not enough information).

Paper fix in 1.0.6.

Big thanks for getting me notified about the bugs - I couldnt really test and find all myself.

**Comment by Weefle** [comment]
Ok, thank you!

**Comment by Weefle** [comment]
Can you please render your project compatible with maven, I have a problem for importing gradle projects.

**Comment by BurnyDaKath** [comment]
It is very easy to import OMGPI in IntelliJ: File -> New -> Project From VC -> GitHub (make sure plugin is installed) -> Type in link you get when pressing "Clone" button on GitHub project's main page -> Clone.

After cloned, press CTRL+ALT+SHIFT+S, go to modules and press "+" button, import each folder you got after cloning (omgpi-main, OMGPI_SW). Agree with everything IntelliJ suggests.

In libraries import Spigot jar for both new modules and OMGPI jar for SW module.

IntelliJ IDEA is my recommendation, and i could not help with any other IDE.

**Comment by Weefle** [comment]
Shit, I use Eclipse and I don't know how to use IntelliJ :/
I'll try it with Eclipse.

**Comment by Weefle** [comment]
OMG I finally did it! :D
